# This file is auto-generated by @hey-api/openapi-python

from typing import Optional

from pydantic import BaseModel, RootModel


class Widget(BaseModel):
    widget_id: str


class WidgetList(BaseModel):
    data: Optional[list[Widget]] = None
    has_more: Optional[bool] = None
    next_cursor: Optional[str] = None


class Gadget(BaseModel):
    gadget_id: str


class GadgetList(BaseModel):
    data: Optional[list[Gadget]] = None


class Thing(BaseModel):
    thing_id: str


class ThingList(BaseModel):
    data: Optional[list[Thing]] = None
    next_cursor: Optional[str] = None


class Sprocket(BaseModel):
    sprocket_id: str


class SprocketList(BaseModel):
    data: Optional[list[Sprocket]] = None
    has_more: Optional[bool] = None
    next_cursor: Optional[str] = None


class ListWidgetsQuery(BaseModel):
    status: Optional[str] = None
    cursor: Optional[str] = None


class ListWidgetsResponse(RootModel[WidgetList]):
    """OK"""

    root: WidgetList


class ListGadgetsResponse(RootModel[GadgetList]):
    """OK"""

    root: GadgetList


class ListThingsQuery(BaseModel):
    cursor: Optional[str] = None


class ListThingsResponse(RootModel[ThingList]):
    """OK"""

    root: ThingList


class ListSprocketsQuery(BaseModel):
    cursor: str


class ListSprocketsResponse(RootModel[SprocketList]):
    """OK"""

    root: SprocketList
