# This file is auto-generated by @hey-api/openapi-python

from typing import Optional

from .client import build_client_params, Client, Page
from .pydantic_gen import GadgetList, SprocketList, ThingList, Widget, WidgetList


class Sdk(Client):
    def list_widgets(self, status: Optional[str] = None, cursor: Optional[str] = None) -> Page[Widget]:
        params = build_client_params([{"in": "query", "key": "status"}, {"in": "query", "key": "cursor"}], status="status", cursor="cursor")
        response = self.client.get("/widgets", params=params)
        page = WidgetList.model_validate(response.json())
        return Page(items=page.data or [], has_more=page.has_more, fetch=self.list_widgets, kwargs={"status": status}, next_params={"cursor": page.next_cursor})

    def list_gadgets(self) -> GadgetList:
        response = self.client.get("/gadgets")
        return GadgetList.model_validate(response.json())

    def list_things(self, cursor: Optional[str] = None) -> ThingList:
        params = build_client_params([{"in": "query", "key": "cursor"}], cursor="cursor")
        response = self.client.get("/things", params=params)
        return ThingList.model_validate(response.json())

    def list_sprockets(self, cursor: str) -> SprocketList:
        params = build_client_params([{"in": "query", "key": "cursor"}], cursor="cursor")
        response = self.client.get("/sprockets", params=params)
        return SprocketList.model_validate(response.json())
